export const usersRegistered = [
  {
    userID: '#1234',
    name: 'Ayomide .A.',
    email: 'ayomijay@gmail.com',
    dateRegistered: '02-12-2024',
    tier: 'Nomad',
    status: 'Active',
    lastLogin: '03-05-2024',
    totalBookedFlights: 24,
    milesAccumulated: '50,000',
  },
  {
    userID: '#1234',
    name: 'Ayomide .A.',
    email: 'ayomijay@gmail.com',
    dateRegistered: '02-12-2024',
    tier: 'Nomad',
    status: 'Inactive',
    lastLogin: '03-05-2024',
    totalBookedFlights: 24,
    milesAccumulated: '50,000',
  },
  {
    userID: '#1234',
    name: 'Ayomide .A. ',
    email: 'ayomijay@gmail.com',
    dateRegistered: '02-12-2024',
    tier: 'Nomad',
    status: 'Active',
    lastLogin: '03-05-2024',
    totalBookedFlights: 24,
    milesAccumulated: '50,000',
  },
  {
    userID: '#1234',
    name: 'Ayomide .A. ',
    email: 'ayomijay@gmail.com',
    dateRegistered: '02-12-2024',
    tier: 'Nomad',
    status: 'Inactive',
    lastLogin: '03-05-2024',
    totalBookedFlights: 24,
    milesAccumulated: '50,000',
  },
];

export const TicketsPurchasedData = [
  {
    transactionID: '2001',
    userID: '#1234',
    name: 'Ayomide .A.',
    email: 'ayomijay@gmail.com',
    dateOfPurchase: '02-23-2024',
    itemPurchased: 'Flight ticket',
    amount: 100,
    paymentMethod: 'Paypal',
    status: 'Completed',
  },
  {
    transactionID: '2001',
    userID: '#1234',
    name: 'Ayomide .A.',
    email: 'ayomijay@gmail.com',
    dateOfPurchase: '02-23-2024',
    itemPurchased: 'Flight ticket',
    amount: 100,
    paymentMethod: 'Credit card',
    status: 'Pending',
  },
  {
    transactionID: '2001',
    userID: '#1234',
    name: 'Ayomide .A.',
    email: 'ayomijay@gmail.com',
    dateOfPurchase: '02-23-2024',
    itemPurchased: 'Baggage',
    amount: 100,
    paymentMethod: 'Paypal',
    status: 'Canceled',
  },
  {
    transactionID: '2001',
    userID: '#1234',
    name: 'Ayomide .A.',
    email: 'ayomijay@gmail.com',
    dateOfPurchase: '02-23-2024',
    itemPurchased: 'Seat upgrade',
    amount: 100,
    paymentMethod: 'Paypal',
    status: 'Completed',
  },
];

export const TotalRevenueData = [
  {
    revenueID: 'R001',
    date: '02-23-2024',
    source: 'Flight ticket',
    amount: 100,
    paymentMethod: 'Paypal',
    channel: 'Paypal',
    country: 'USA',
    currency: 'USD',
    transactionCount: 20,
  },
  {
    revenueID: 'R002',
    date: '02-23-2024',
    source: 'Flight ticket',
    amount: 100,
    paymentMethod: 'Paypal',
    channel: 'Paypal',
    country: 'UK',
    currency: 'GBP',
    transactionCount: 30,
  },
  {
    revenueID: 'R003',
    date: '02-23-2024',
    source: 'Baggage',
    amount: 100,
    paymentMethod: 'Paypal',
    channel: 'Paypal',
    country: 'India',
    currency: 'INR',
    transactionCount: 10,
  },
  {
    revenueID: 'R004',
    date: '02-23-2024',
    source: 'Seat upgrade',
    amount: 100,
    paymentMethod: 'Paypal',
    channel: 'Paypal',
    country: 'Nigeria',
    currency: 'Naira',
    transactionCount: 50,
  },
  {
    revenueID: 'R005',
    date: '02-23-2024',
    source: 'Seat upgrade',
    amount: 100,
    paymentMethod: 'Paypal',
    channel: 'Mobile transfer',
    country: 'Spain',
    currency: 'EUR',
    transactionCount: 20,
  },
];

export const ActiveUsersData = [
  {
    monthYear: 'Jan 2024',
    totalActiveUsers: 25000,
    newRegistration: 5000,
    returningUsers: 3000,
    churnRate: 10,
    totalSessions: 100000,
    averageSessionDuration: '15 mins',
    geographicalDistribution: [
      { country: 'USA', population: 10000 },
      { country: 'UK', population: 12000 },
      { country: 'Nigeria', population: 25000 },
      { country: 'IND', population: 5000 },
      { country: 'Others', population: 7000 },
    ],
    deviceDistribution: [
      { deviceType: 'IOS', count: 12000 },
      { deviceType: 'Android', count: 15000 },
    ],
  },
  {
    monthYear: 'Feb 2024',
    totalActiveUsers: 27000,
    newRegistration: 6000,
    returningUsers: 2500,
    churnRate: 8,
    totalSessions: 80000,
    averageSessionDuration: '15 mins',
    geographicalDistribution: [
      { country: 'USA', population: 10000 },
      { country: 'UK', population: 12000 },
      { country: 'Nigeria', population: 25000 },
      { country: 'IND', population: 5000 },
      { country: 'Others', population: 7000 },
    ],
    deviceDistribution: [
      { deviceType: 'IOS', count: 12000 },
      { deviceType: 'Android', count: 15000 },
    ],
  },
  {
    monthYear: 'Mar 2024',
    totalActiveUsers: 30000,
    newRegistration: 5500,
    returningUsers: 1500,
    churnRate: 9,
    totalSessions: 110000,
    averageSessionDuration: '14 mins',
    geographicalDistribution: [
      { country: 'USA', population: 10000 },
      { country: 'UK', population: 12000 },
      { country: 'Nigeria', population: 25000 },
      { country: 'IND', population: 5000 },
      { country: 'Others', population: 7000 },
    ],
    deviceDistribution: [
      { deviceType: 'IOS', count: 12000 },
      { deviceType: 'Android', count: 15000 },
    ],
  },
  {
    monthYear: 'Apr 2024',
    totalActiveUsers: 22000,
    newRegistration: 2500,
    returningUsers: 1000,
    churnRate: 8,
    totalSessions: 80000,
    averageSessionDuration: '16 mins',
    geographicalDistribution: [
      { country: 'USA', population: 10000 },
      { country: 'UK', population: 12000 },
      { country: 'Nigeria', population: 25000 },
      { country: 'IND', population: 5000 },
      { country: 'Others', population: 7000 },
    ],
    deviceDistribution: [
      { deviceType: 'IOS', count: 12000 },
      { deviceType: 'Android', count: 15000 },
    ],
  },
  {
    monthYear: 'May 2024',
    totalActiveUsers: 50000,
    newRegistration: 3000,
    returningUsers: 800,
    churnRate: 5,
    totalSessions: 100000,
    averageSessionDuration: '16 mins',
    geographicalDistribution: [
      { country: 'USA', population: 10000 },
      { country: 'UK', population: 12000 },
      { country: 'Nigeria', population: 25000 },
      { country: 'IND', population: 5000 },
      { country: 'Others', population: 7000 },
    ],
    deviceDistribution: [
      { deviceType: 'IOS', count: 12000 },
      { deviceType: 'Android', count: 15000 },
    ],
  },
  {
    monthYear: 'June 2024',
    totalActiveUsers: 10000,
    newRegistration: 3500,
    returningUsers: 900,
    churnRate: 4,
    totalSessions: 100000,
    averageSessionDuration: '15 mins',
    geographicalDistribution: [
      { country: 'USA', population: 10000 },
      { country: 'UK', population: 12000 },
      { country: 'Nigeria', population: 25000 },
      { country: 'IND', population: 5000 },
      { country: 'Others', population: 7000 },
    ],
    deviceDistribution: [
      { deviceType: 'IOS', count: 12000 },
      { deviceType: 'Android', count: 15000 },
    ],
  },
];
